import { createAccessControl } from "better-auth/plugins/access";
import { defaultStatements } from "better-auth/plugins/admin/access";

const PROJECT_PERMISSION_CODES = {
    VIEW_DASHBOARD: "VIEW_DASHBOARD",
    CREATE_CHILD: "CREATE_CHILD",
    EDIT_CHILD: "EDIT_CHILD",
    DELETE_CHILD: "DELETE_CHILD",
    EDIT_CALENDAR: "EDIT_CALENDAR",
    GENERATE_RECIEPTS: "GENERATE_RECIEPTS",
    GENERATE_SIGNIN_SHEET: "GENERATE_SIGNIN_SHEET",
    GENERATE_EMERGENCY_ROSTER: "GENERATE_EMERGENCY_ROSTER",
    GENERATE_TECHER_SIGNIN_SHEET: "GENERATE_TECHER_SIGNIN_SHEET",
} as const;

type ProjectPermissionKey = keyof typeof PROJECT_PERMISSION_CODES;
type ProjectPermission = typeof PROJECT_PERMISSION_CODES[ProjectPermissionKey];

export const PROJECT_PERMISSIONS: ProjectPermission[] = Object.values(PROJECT_PERMISSION_CODES);

export const USER_PRIVILEGES = [PROJECT_PERMISSION_CODES.VIEW_DASHBOARD,
    PROJECT_PERMISSION_CODES.GENERATE_SIGNIN_SHEET,PROJECT_PERMISSION_CODES.GENERATE_EMERGENCY_ROSTER,
PROJECT_PERMISSION_CODES.GENERATE_TECHER_SIGNIN_SHEET ];


export const ADMIN_PRIVILEGES = Object.values(PROJECT_PERMISSION_CODES);


